### ISSUE TITLE
Extend typescript parser

### ISSUE THREAD

**Issue by corysimmons** [abhijithvijayan/eslint-config#5]
https://github.com/abhijithvijayan/eslint-config/blob/3e16b2ba65148a005340c4ff18ca421f777cc9ed/index.js#L10

You need to add the typescript.js config (with the typescript parser) here.

**Comment by abhijithvijayan** [comment]
What's wrong with splitting js & ts apart?

`@abhijithvijayan/eslint-config` for JavaScript (default `index.js`)

`@abhijithvijayan/eslint-config/typescript` for TypeScript

**Comment by abhijithvijayan** [comment]
Initially both the configuration was in one single file and the eslint was throwing typescript errors for javascript alone projects.

This seemed like a good way to split for the two sorts of projects.

May I know why you are suggesting to add typescript config to the default module?
